### ISSUE TITLE
Backslashes disappearing when saving

### ISSUE THREAD

**Issue by Edzilla2000** [turnermm/ckgdoku#27] opened 2017-08-18 10:27 UTC
If I edit a page and then save it, it seems that backslashes are disappearing: 
For example, this: 
`C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command`
turns into 
`C:WindowsSystem32WindowsPowerShellv1.0powershell.exe -command`

**Comment by turnermm** [comment] 2017-08-18 13:08
I can't reproduce this: https://mturner.org/devel/playground/links2#windows_paths
There is probably something more involved, like another plugin, or browser (though it tests OK in Edge and IE on Windows 10).

**Comment by Edzilla2000** [comment] 2017-08-22 14:29
I'm using firefox 55.0.1 on windows 10
plugins are lastpass, pushbullet and ublock origin

**Comment by turnermm** [comment] 2017-08-22 14:42
I  tried it on all Windows 10 available browsers including ff 55.02.  Can't reproduce it.  Try disabling all the plugins.  If successful, then re-enable them one at a time, to see which is causing the problem.  Otherwise provide the full page context where this happens.

**Comment by Edzilla2000** [comment] 2017-12-07 17:23
Sorry for not replying earlier, this had slipped my mind.
I made tests to try and find out if some plugin was causing this, but I have this issue even with all non bundled plugins disabled.
However I was able to reproduce it with this: 
https://pastebin.com/rhB2hkZW

**Comment by turnermm** [comment] 2017-12-07 18:06
Are you sure this is the correct pastebin? It has no backslashes.

**Comment by Edzilla2000** [comment] 2017-12-08 07:33
Sorry, I created the paste from the page where the backslash had been removed.
Here it is with the backslash: https://pastebin.com/DFVAtkgk

**Comment by turnermm** [comment] 2017-12-08 21:40
This should be fixed in lastest update.

**Comment by Edzilla2000** [comment] 2017-12-08 21:56
Indeed, perfect, thanks!

**Comment by kerlerm** [comment] 2017-12-19 08:18
Single backslashes are handled correctly since 2017-12-08 release. But codeblocks containing double backslashes are still reduced to single backslashes.

`\\samba\share\`
gets
`\samba\share\`

Please reopen. Thx.

**Comment by turnermm** [comment] 2017-12-22 14:58
I'm afraid I am not getting this.  See:
https://mturner.org/devel/playground/code_block

I'll need the entire context.

**Comment by kerlerm** [comment] 2018-01-02 07:48
Sorry for the late answer - been on holidays. Happy New Year to you :)


https://pastebin.com/Vvt9VTSV


... shortens the double backslash to a single backslash when saving with ckgdoku. This seems to be caused by the interwiki link after the file block.

**Comment by turnermm** [comment] 2018-01-02 14:39
I hope this is now fixed.  I think it is.  And Happy New Year to you.

**Comment by kerlerm** [comment] 2018-01-03 08:08
This is fixed. Thanks a lot!

...but only for the first code/file block. In the next block the double backslash disappears again...
https://pastebin.com/KNVyuSMe

**Comment by kerlerm** [comment] 2018-01-08 15:47
Could you reopen this issue, please? Thanks.

**Comment by turnermm** [comment] 2018-01-09 17:47
Should be OK now.

**Comment by kerlerm** [comment] 2018-01-10 08:08
Almost fixed :)

If there is a "pipe" operator in following code blocks, the double backslashes disappear again...
https://pastebin.com/aZLC7mcb

**Comment by turnermm** [comment] 2018-01-10 14:14
Clear  out your Dokuwiki cache directory and your browser cache.

**Comment by kerlerm** [comment] 2018-01-10 15:24
I did empty the browser cache and invalidated dokuwiki cache by touching conf/local.php. The issue persists.

**Comment by turnermm** [comment] 2018-01-10 15:54
Unfortunately, I can't reproduce it using  your example code

**Comment by kerlerm** [comment] 2018-01-11 08:26
my workflow: 

- touch conf/local.php & empty browser cache
- edit playground page
- switch to "DW Edit"
- insert pastebin code block https://pastebin.com/aZLC7mcb
- save
- result: OK
- edit playground page
- switch to "CKG Editor"
- touch conf/local.php & empty browser cache
- edit playground page
- add even more backslashes in code block e.g. triple backslash - samba - double backslash - test - double backslash
- save

result: number of backslashes in code blocks are reduced depending on their position in the string. Especially leading and trailing backslashes are removed.

**Comment by turnermm** [comment] 2018-01-11 10:49
Try it now.

**Comment by turnermm** [comment] 2018-01-11 17:34
I continued to work on this.  Getting an algorithm that has no unintended side-effects while at the same time covering all possible cases has been a challenge.  You might want to try this now.

**Comment by kerlerm** [comment] 2018-01-11 18:51
Thanks for your efforts! I will give it a go tomorrow morning...

**Comment by kerlerm** [comment] 2018-01-12 14:09
This is fixed now - at least for my use-case. Thanks a lot!

**Comment by turnermm** [comment] 2018-01-12 14:49
Thanks.  I'll keep playing with it until I find something that works in the most complex cases, cases that it's hard to imagine anyone using!

**Closed as completed** 2018-07-27 12:03 UTC
